FROM node:20.18.0 as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

ARG NEXT_PUBLIC_BASE_URL=https://ifex-2027-event-service.eventstrat.ai
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL

RUN npm run build 

EXPOSE 8083

CMD ["npm", "run", "start"]