server {
    listen 80;
    server_name exhibitor.bharat-tex.com;

    location / {
        proxy_pass http://exhibitor-node:8083;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    # Optional: For serving static assets directly by Nginx
    #location /_next/static {
    #    alias /home/ubuntu/exhibitor-panel/.next/static;
    #    expires 1y;
    #    access_log off;
    #}   
}
