[supervisord]
nodaemon=true

[program:node]
command=/bin/bash -c "npm run start"
directory=/app
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/node.log
stderr_logfile=/var/log/supervisor/node.err.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
