// ----------------------------------------------------------------------

export const PRODUCT_GENDER_OPTIONS = [
  { value: 'exhibition', label: 'Exhibition' },
  { value: 'conference', label: 'Conference' },
  { value: 'trade_show', label: 'Trade Show' },
];

export const PRODUCT_CATEGORY_OPTIONS = [
  'All',
  'Stage Equipment',
  'Audio Systems',
  'Lighting',
  'Display Stands',
  'Furniture',
  'Digital Displays',
  'Booth Materials',
  'Storage Solutions',
];

export const PRODUCT_RATING_OPTIONS = ['up4Star', 'up3Star', 'up2Star', 'up1Star'];

export const PRODUCT_COLOR_OPTIONS = [
  { value: 'black', label: 'Black' },
  { value: 'white', label: 'White' },
  { value: 'silver', label: 'Silver' },
  { value: 'wood', label: 'Wood' },
];

export const PRODUCT_SORT_OPTIONS = [
  { value: 'featured', label: 'Featured' },
  { value: 'newest', label: 'Newest' },
  { value: 'priceDesc', label: 'Price: High-Low' },
  { value: 'priceAsc', label: 'Price: Low-High' },
];

// ----------------------------------------------------------------------

export const products = [
  {
    id: '1',
    sku: 'LED-STAGE-001',
    name: 'Professional LED Stage Lighting Kit',
    code: 'LED001',
    price: 2999.99,
    taxes: 299.99,
    tags: ['lighting', 'stage', 'professional'],
    gender: 'exhibition',
    sizes: ['small', 'medium', 'large'],
    publish: 'published',
    coverUrl: '/assets/images/products/stage-light-1.jpg',
    images: [
      '/assets/images/products/stage-light-1.jpg',
      '/assets/images/products/stage-light-2.jpg',
      '/assets/images/products/stage-light-3.jpg',
    ],
    colors: ['black', 'silver'],
    quantity: 50,
    category: 'Lighting',
    available: 45,
    totalSold: 155,
    description: 'Professional LED stage lighting kit with DMX control and multiple effects',
    totalRatings: 4.8,
    totalReviews: 89,
    inventoryType: 'in_stock',
    subDescription: 'Perfect for exhibitions and trade shows',
    priceSale: 2499.99,
    reviews: [
      {
        id: 'review1',
        name: 'John Smith',
        rating: 5,
        comment: 'Excellent lighting system, perfect for our exhibition booth',
        helpful: 15,
        avatarUrl: '/assets/images/avatars/avatar_1.jpg',
        isPurchased: true,
        postedAt: '2024-01-15',
      },
    ],
    createdAt: '2023-12-01',
    ratings: [
      { name: '5 Stars', starCount: 5, reviewCount: 45 },
      { name: '4 Stars', starCount: 4, reviewCount: 30 },
      { name: '3 Stars', starCount: 3, reviewCount: 10 },
      { name: '2 Stars', starCount: 2, reviewCount: 3 },
      { name: '1 Star', starCount: 1, reviewCount: 1 },
    ],
    saleLabel: {
      enabled: true,
      content: '17% Off',
    },
    newLabel: {
      enabled: true,
      content: 'New',
    },
  },
  {
    id: '2',
    sku: 'AUD-SYS-002',
    name: 'Premium Audio System Package',
    code: 'AUD002',
    price: 4999.99,
    taxes: 499.99,
    tags: ['audio', 'sound', 'professional'],
    gender: 'conference',
    sizes: ['medium', 'large'],
    publish: 'published',
    coverUrl: '/assets/images/products/audio-system-1.jpg',
    images: [
      '/assets/images/products/audio-system-1.jpg',
      '/assets/images/products/audio-system-2.jpg',
      '/assets/images/products/audio-system-3.jpg',
    ],
    colors: ['black'],
    quantity: 30,
    category: 'Audio Systems',
    available: 25,
    totalSold: 120,
    description: 'Complete audio system package with speakers, mixer, and wireless microphones',
    totalRatings: 4.9,
    totalReviews: 75,
    inventoryType: 'in_stock',
    subDescription: 'Ideal for conferences and large events',
    priceSale: null,
    reviews: [
      {
        id: 'review2',
        name: 'Sarah Johnson',
        rating: 5,
        comment: 'Crystal clear sound quality, perfect for our conference',
        helpful: 20,
        avatarUrl: '/assets/images/avatars/avatar_2.jpg',
        isPurchased: true,
        postedAt: '2024-01-20',
      },
    ],
    createdAt: '2023-11-15',
    ratings: [
      { name: '5 Stars', starCount: 5, reviewCount: 50 },
      { name: '4 Stars', starCount: 4, reviewCount: 20 },
      { name: '3 Stars', starCount: 3, reviewCount: 5 },
      { name: '2 Stars', starCount: 2, reviewCount: 0 },
      { name: '1 Star', starCount: 1, reviewCount: 0 },
    ],
    saleLabel: {
      enabled: false,
      content: '',
    },
    newLabel: {
      enabled: true,
      content: 'New',
    },
  },
  {
    id: '3',
    sku: 'DSP-STD-003',
    name: 'Modular Display Stand System',
    code: 'DSP003',
    price: 1499.99,
    taxes: 149.99,
    tags: ['display', 'modular', 'booth'],
    gender: 'trade_show',
    sizes: ['small', 'medium', 'large'],
    publish: 'published',
    coverUrl: '/assets/images/products/display-stand-1.jpg',
    images: [
      '/assets/images/products/display-stand-1.jpg',
      '/assets/images/products/display-stand-2.jpg',
      '/assets/images/products/display-stand-3.jpg',
    ],
    colors: ['silver', 'black', 'white'],
    quantity: 40,
    category: 'Display Stands',
    available: 35,
    totalSold: 200,
    description: 'Customizable modular display stand system for trade shows',
    totalRatings: 4.7,
    totalReviews: 95,
    inventoryType: 'in_stock',
    subDescription: 'Easy to assemble and transport',
    priceSale: 1299.99,
    reviews: [
      {
        id: 'review3',
        name: 'Mike Wilson',
        rating: 4,
        comment: 'Very versatile and easy to set up',
        helpful: 12,
        avatarUrl: '/assets/images/avatars/avatar_3.jpg',
        isPurchased: true,
        postedAt: '2024-01-18',
      },
    ],
    createdAt: '2023-12-15',
    ratings: [
      { name: '5 Stars', starCount: 5, reviewCount: 55 },
      { name: '4 Stars', starCount: 4, reviewCount: 25 },
      { name: '3 Stars', starCount: 3, reviewCount: 10 },
      { name: '2 Stars', starCount: 2, reviewCount: 4 },
      { name: '1 Star', starCount: 1, reviewCount: 1 },
    ],
    saleLabel: {
      enabled: true,
      content: '13% Off',
    },
    newLabel: {
      enabled: false,
      content: '',
    },
  },
  {
    id: '4',
    sku: 'FRN-SET-004',
    name: 'Exhibition Furniture Set',
    code: 'FRN004',
    price: 2499.99,
    taxes: 249.99,
    tags: ['furniture', 'booth', 'seating'],
    gender: 'exhibition',
    sizes: ['medium', 'large'],
    publish: 'published',
    coverUrl: '/assets/images/products/furniture-set-1.jpg',
    images: [
      '/assets/images/products/furniture-set-1.jpg',
      '/assets/images/products/furniture-set-2.jpg',
      '/assets/images/products/furniture-set-3.jpg',
    ],
    colors: ['wood', 'black', 'white'],
    quantity: 25,
    category: 'Furniture',
    available: 20,
    totalSold: 150,
    description: 'Complete furniture set including counter, chairs, and display units',
    totalRatings: 4.6,
    totalReviews: 82,
    inventoryType: 'in_stock',
    subDescription: 'Modern design perfect for exhibition booths',
    priceSale: null,
    reviews: [
      {
        id: 'review4',
        name: 'Emily Brown',
        rating: 5,
        comment: 'High-quality furniture that looks great in our booth',
        helpful: 18,
        avatarUrl: '/assets/images/avatars/avatar_4.jpg',
        isPurchased: true,
        postedAt: '2024-01-22',
      },
    ],
    createdAt: '2023-11-30',
    ratings: [
      { name: '5 Stars', starCount: 5, reviewCount: 42 },
      { name: '4 Stars', starCount: 4, reviewCount: 28 },
      { name: '3 Stars', starCount: 3, reviewCount: 8 },
      { name: '2 Stars', starCount: 2, reviewCount: 3 },
      { name: '1 Star', starCount: 1, reviewCount: 1 },
    ],
    saleLabel: {
      enabled: false,
      content: '',
    },
    newLabel: {
      enabled: true,
      content: 'New',
    },
  },
];

// ----------------------------------------------------------------------

export const product = products[0];
