export interface IExhibitorFormData {
  companyAddress: string;
  companyContact: string;
  companyEmail: string;
  companyGstin: string | null;
  companyOrganizationName: string;
  companyPanNo: string;
  data: {
    udyogAadhaarNumber: string;
    accountPersonEmailAddress: string;
    accountPersonFirstName: string;
    accountPersonLastName: string;
    accountPersonMobileNumber: string;
    additionalDirectors: string[];
    addressLine1: string;
    billingAddressLine1: string;
    billingAddressLine2: string;
    billingCity: string;
    billingCountry: string;
    billingPostalCode: string;
    billingStateProvinceRegion: string;
    bookingViaAssociation: string;
    boothDisplayName: string;
    boothTypePreference: string;
    calculatedTotalCost: number;
    city: string;
    contactPersonDesignation: string;
    country: string;
    departmentCategory: string;
    hasGstNumber: string;
    interestedInSponsorship: string;
    mainObjectives: string[];
    participatedEarlier: string;
    postalCode: string;
    productCategory: string;
    registeredWithMsme: string;
    signatureUrl: string;
    stateProvinceRegion: string;
    tanNumber: string;
    tds: string;
    totalAreaRequired: number;
    proformaInvoice:string;
  };
  directorName: string;
  email: string;
  eventId: number;
  firstName: string;
  image: string;
  imgUrl: string | null;
  lastName: string;
  phone: string;
  userCohort: string;
}
